### ISSUE TITLE
2021 - OWASP Global Board Election Call for Questions

### ISSUE THREAD

**Issue by hblankenship** [OWASP-Foundation/Board-Election-Call-for-Questions#5]
Please post your questions as comments to this issue. For questions you like, you can 'upvote' them by clicking the 'thumbs up' icon. This call for questions will begin on August 15th, 2021 and end on August 31st, 2021.

Please submit only one question per comment so that the individual questions may be upvoted.

**Comment by PBDataRecon** [comment]
Automation and now AI have been good for AppSec in that it has increased the speed of releases, improved detection of coding flaws and reduced overall operating costs. At the same time, jobs in AppSec are moving from analyst positions to lower paid engineering positions. What do you see as being OWASP's role in the industry in ten years and how would you begin to position OWASP to get there?

**Comment by ErezYalon** [comment]
OWASP has great resources for different people and different roles: CISOs, AppSec Managers, Pentersters, Analysts, Developers, DevOps, QA, and even users. Currently, most of them are either not aware of OWASP, or consider OWASP as a short for the "OWASP Top 10". What practical steps should OWASP take to change that?

**Comment by dune73** [comment]
What experience do you bring serving in a board or executive committee of a large international organization or project?

**Comment by 139381512412** [comment]
How will you enable members to grow OWASP in their localities. The local chapter seems to have disbanded before I even knew it existed and there's not a strong mechanism to regrow it that I see.

**Comment by thombrem** [comment]
> What experience do you bring serving in a board or executive committee of a large international organization or project?

Hi dune73,

I have been working in the software product dev and IT services space since my graduation in 1995. I have worked in various capacities and at different levels from the ground up. This experience includes running my own startups in this space. 

That being said, I do not wish to harp on my rather small bits of experience at the helm. On the contrary, I would argue that being a hands-on developer, I bring in a fresh perspective which may help the organization in novel ways going forth.

~Milind

**Comment by thombrem** [comment]
> How will you enable members to grow OWASP in their localities. The local chapter seems to have disbanded before I even knew it existed and there's not a strong mechanism to regrow it that I see.

I will share my own personal experience of being an OWASP member here. I hardly get any communication or useful tools for ready use from OWASP. No product upgrade announcements or new open source projects being conceptualized. This will be the first thing I correct. "Communication" is key in keeping a community going as are "Shared Goals" It is not that people are not aware of OWASP or are not attracted by what it has to offer, they simply do not see what is happening under the hood, and simply drift away and choose to devote time to other fora.

I believe, frequent, relevant and timely communication and the sharing of Goals and Vision will keep local chapters together as much as a collaborative spirit and camaraderie amongst its members!

Thx, Milind

**Comment by thombrem** [comment]
> Automation and now AI have been good for AppSec in that it has increased the speed of releases, improved detection of coding flaws and reduced overall operating costs. At the same time, jobs in AppSec are moving from analyst positions to lower paid engineering positions. What do you see as being OWASP's role in the industry in ten years and how would you begin to position OWASP to get there?

The march towards increased automation has begun a while back in all walks of life, including a technologists daily routine. While, I have no solution for the issue of the reducing number of jobs caused by automation, I do believe there will be a spurt in opportunities for those creating the automation. It changes tech for the better, for users, but, changes the very paradigm that an AppSec professional must wake up and go to work, for the rest of his life! This is no longer about costs alone, but speed, accuracy and error-free operation come with Automation....eventually.

Here is my proposal:

1. The goal of OWASP must be to contribute towards automation and not stand in the way
2. We must involve the community resources in doing so
3. We should continue to build a thriving community of AppSec developers and professionals knowing that the nature of threats will change and become even more complex in the future.
4. Lastly, we should also begin creating a fund for those who lose their means of livelihood, from within our community, as a result of Automation. Who would contribute to this fund? The very "For-Profit" corporations who will benefit from the AppSec Automation Tools OWASP will create for them!

My 2 cents!

~Milind

**Comment by act1vand0** [comment]
> @thombrem I totally appreciate your enthusiasm, but I think this ticket is just for collecting and voting on questions, of which the highest ranked will be given to board candidates to answer. Mixing in answers here will make it very confusing for people to check what is what and where to upvote.

I second this. I'd kindly and with all due respect suggest to actually delete the comments which are responses to the questions since, as @bkimminich says, it may confuse people and even encourage other participants to add responses here, which doesn't seem the right place. Cheers.

**Comment by act1vand0** [comment]
What are the three main things you'd focus on changing/improving for OWASP as an organization, and why?

**Comment by anantshri** [comment]
For existing members appearing for re-election : 

Can you please provide an overview of what you wanted to do in last tenure and how much of it you could achieve. (If its not much then what was the reason)

**Comment by anantshri** [comment]
covid-19 has had a major impact on OWASP's major earning sources, which were conference tickets / training tickets. What will you do to ensure a more balanced funding sources in the future?

**Comment by Anwar-Faiz** [comment]
1. What interests you about serving on the Global board of OWASP?
2. What skills you would bring in and the ideas you have to support OWASP through development opportunities via global board.

**Comment by bkimminich** [comment]
How do you plan to establish/improve/continue* the exchange between OWASP board and community and how will this ensure that you represent the broader community's interests in the best possible way?

(*pick the verb best matching your point of view on the current situation)

**Comment by anantshri** [comment]
As an entry in OWASP Board Elections, can you provide details of what are your contribution/involvement to OWASP so far. 

Why this question: We get a lot of nominations. This will help people position your argument considering your work so far and your involvement with OWASP community.
